server:
  port: 80
  
spring:
  application:
    name: cw-framework
    
logging:
  level:
    root: info
    com.cw.framework: info
    
app:
  license:
    bypass: false  # 生产环境启用许可证校验
    
# JNA原生库路径配置
jna:
  library:
    path: classpath:native 