server:
  port: 8080
  
spring:
  application:
    name: cw-framework-dev
    
logging:
  level:
    root: debug
    com.cw.framework: debug
    
app:
  license:
    bypass: true  # 开发环境跳过许可证校验
    
# JNA原生库路径配置
jna:
  library:
    path: classpath:native 