server:
  port: 8080

spring:
  application:
    name: cw-framework
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:logback.xml
  level:
    root: info
    com.cw.framework: debug

app:
  license:
    key: ${LICENSE_KEY:default-license-key-for-development}  # 从环境变量或系统属性中获取，默认为开发密钥
    bypass: ${APP_LICENSE_BYPASS:true}  # 本地环境默认跳过许可证校验

# JNA原生库路径配置
jna:
  library:
    path: ${JNA_LIBRARY_PATH:classpath:native}

# 微信支付配置
wechat:
  pay:
    v2:
      appId: wxc8e476e988b19b9b #微信公众号或者小程序等的appid
      mchId: 1682631904 #微信支付商户号
      mchKey: 351ae355c9fc063ec054fb3e50d14323 #微信支付商户密钥
      notify-url: /payNotify
    v3:
      # 小程序AppID
      appid: wx1234567890abcdef
      # 商户号
      mchId: 1234567890
      # 商户私钥文件路径
      private-key-path: /path/to/apiclient_key.pem
      # 商户证书序列号
      merchant-serial-number: 3B92C5A7B0B8C1D2E3F4A5B6C7D8E9F0A1B2C3D4
      # API v3密钥
      api-v3-key: your-api-v3-key-32-characters-long
      # 支付结果通知地址
      notify-url: https://your-domain.com/api/wechat/pay/notify